softdep nvidia pre: vfio-pci
softdep nvidia_drm pre: vfio-pci
softdep amdgpu pre: vfio-pci
softdep snd_hda_intel pre: vfio-pci
softdep xhci_hcd pre: vfio-pci
softdep brcmfmac pre: vfio-pci
softdep igb pre: vfio-pci
softdep nvme pre: vfio-pci
softdep ahci pre: vfio-pci
options vfio-pci ids=144d:a808,1b21:0612,1b21:2142,8086:15b8 disable_vga=1
options vfio_iommu_type1 allow_unsafe_interrupts=1
