set -g default-shell /bin/zsh

set -g default-terminal "xterm-256color"
set -sg terminal-overrides ",*:RGB"

set-option -g focus-events on

# Change prefix to Ctrl-A
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Start windows and panes index from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Reload config with Prefix-R
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Split in panes using a easier to remember key
bind | split-window -h
bind - split-window -v

set -g history-limit 5000

# VIM mode
setw -g mode-keys vi

# VIM Movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# VIM Resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Fix ESC delay
set -sg escape-time 10

# Enable mouse support
set -g mouse on

# don't suspend-client
unbind-key C-z

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'jfturcot/catppuccin-tmux'
set -g @catppuccin_flavour 'frappe' # latte,frappe, macchiato or mocha

set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
